/**
 * Auto-generated route constants from OpenAPI schema
 * Generated at: 2025-10-08T12:43:18.604Z
 * Do not edit this file manually - run this script to update
 */

// UI-only (session/cookies; unversioned)
export const DASHBOARD_ROUTES = {
  REGISTER_NEW_USER: '/auth/register',
  USER_LOGIN: '/auth/login',
} as const;

// Management API (versioned)
export const MGMT_V1_ROUTES = {
  API_KEYS: {
    CREATE_API_KEY: '/v1/api-keys',
    LIST_API_KEYS: '/v1/api-keys',
    REVOKE_API_KEY: '/v1/api-keys/:id',
  },
  DATA: {
    GET_EVENT_LOGS: '/v1/data/logs',
    GET_USAGE_STATISTICS: '/v1/data/usage',
  },
  RULES: {
    GET_AVAILABLE_RULES: '/v1/rules',
    GET_REASON_CODE_CATALOG: '/v1/rules/catalog',
    REGISTER_CUSTOM_RULES: '/v1/rules/register',
  },
  WEBHOOKS: {
    TEST_WEBHOOK: '/v1/webhooks/test',
  },
} as const;

// Runtime API
export const API_V1_ROUTES = {
  DEDUPE: {
    DEDUPLICATE_ADDRESS: '/v1/dedupe/address',
    DEDUPLICATE_CUSTOMER: '/v1/dedupe/customer',
    MERGE_DEDUPLICATED_RECORDS: '/v1/dedupe/merge',
  },
  ORDERS: {
    EVALUATE_ORDER_FOR_RISK_AND_RULES: '/v1/orders/evaluate',
  },
  VALIDATE: {
    VALIDATE_ADDRESS: '/v1/validate/address',
    VALIDATE_EMAIL_ADDRESS: '/v1/validate/email',
    VALIDATE_PHONE_NUMBER: '/v1/validate/phone',
    VALIDATE_TAX_ID: '/v1/validate/tax-id',
  },
  VERIFY: {
    VERIFY_PHONE_OTP: '/v1/verify/phone',
  },
} as const;
