/**
 * Auto-generated route constants from OpenAPI schema
 * Generated at: 2025-10-07T20:04:06.635Z
 * Do not edit this file manually - run generate-routes.js to update
 */

export const DASHBOARD_ROUTES = {
  REGISTER_NEW_USER: '/auth/register',
  USER_LOGIN: '/auth/login',
  LIST_API_KEYS: '/api-keys',
  CREATE_API_KEY: '/api-keys',
  REVOKE_API_KEY: '/api-keys/:id',
  GET_EVENT_LOGS: '/data/logs',
  GET_USAGE_STATISTICS: '/data/usage',
  TEST_WEBHOOK: '/webhooks/test',
} as const;

// API routes (with v1 prefix)
export const API_V1_ROUTES = {
  VALIDATE: {
    VALIDATE_EMAIL_ADDRESS: '/v1/validate/email',
    VALIDATE_PHONE_NUMBER: '/v1/validate/phone',
    VALIDATE_ADDRESS: '/v1/validate/address',
    VALIDATE_TAX_ID: '/v1/validate/tax-id',
  },
  VERIFY: {
    VERIFY_PHONE_OTP: '/v1/verify/phone',
  },
  DEDUPE: {
    DEDUPLICATE_CUSTOMER: '/v1/dedupe/customer',
    DEDUPLICATE_ADDRESS: '/v1/dedupe/address',
    MERGE_DEDUPLICATED_RECORDS: '/v1/dedupe/merge',
  },
  ORDERS: {
    EVALUATE_ORDER_FOR_RISK_AND_RULES: '/v1/orders/evaluate',
  },
  RULES: {
    GET_AVAILABLE_RULES: '/v1/rules',
    GET_REASON_CODE_CATALOG: '/v1/rules/catalog',
    REGISTER_CUSTOM_RULES: '/v1/rules/register',
  },
} as const;

