/**
 * Auto-generated route constants from OpenAPI schema
 * Generated at: 2025-10-11T15:20:52.873Z
 * Do not edit this file manually - run this script to update
 */

// UI-only (session/cookies; unversioned)
export const DASHBOARD_ROUTES = {
  REGISTER_NEW_USER: '/auth/register',
  USER_LOGIN: '/auth/login',
  USER_LOGOUT: '/auth/logout',
} as const;

// Management API (versioned)
export const MGMT_V1_ROUTES = {
  API_KEYS: {
    CREATE_API_KEY: '/v1/api-keys',
    LIST_API_KEYS: '/v1/api-keys',
    REVOKE_API_KEY: '/v1/api-keys/:id',
  },
  DATA: {
    ERASE_USER_DATA: '/v1/data/erase',
    GET_EVENT_LOGS: '/v1/data/logs',
    GET_USAGE_STATISTICS: '/v1/data/usage',
  },
  LOGS: {
    DELETE_LOG_ENTRY: '/v1/logs/:id',
  },
  RULES: {
    GET_AVAILABLE_RULES: '/v1/rules',
    GET_REASON_CODE_CATALOG: '/v1/rules/catalog',
    REGISTER_CUSTOM_RULES: '/v1/rules/register',
  },
  SETTINGS: {
    GET_TENANT_SETTINGS: '/v1/settings',
    UPDATE_TENANT_SETTINGS: '/v1/settings',
  },
  WEBHOOKS: {
    CREATE_WEBHOOK: '/v1/webhooks',
    DELETE_WEBHOOK: '/v1/webhooks/:id',
    LIST_WEBHOOKS: '/v1/webhooks',
    TEST_WEBHOOK: '/v1/webhooks/test',
  },
} as const;

// Runtime API
export const API_V1_ROUTES = {
  BATCH: {
    BATCH_DEDUPLICATE_DATA: '/v1/batch/dedupe',
    BATCH_VALIDATE_DATA: '/v1/batch/validate',
  },
  DEDUPE: {
    DEDUPLICATE_ADDRESS: '/v1/dedupe/address',
    DEDUPLICATE_CUSTOMER: '/v1/dedupe/customer',
    MERGE_DEDUPLICATED_RECORDS: '/v1/dedupe/merge',
  },
  JOBS: {
    GET_JOB_STATUS: '/v1/jobs/:id',
  },
  ORDERS: {
    EVALUATE_ORDER_FOR_RISK_AND_RULES: '/v1/orders/evaluate',
  },
  VALIDATE: {
    VALIDATE_ADDRESS: '/v1/validate/address',
    VALIDATE_EMAIL_ADDRESS: '/v1/validate/email',
    VALIDATE_PHONE_NUMBER: '/v1/validate/phone',
    VALIDATE_TAX_ID: '/v1/validate/tax-id',
  },
  VERIFY: {
    VERIFY_PHONE_OTP: '/v1/verify/phone',
  },
} as const;
