/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * OrbitCheck API
 * API for validation, deduplication, and risk assessment services
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * Current plan details
 */
export type UserPlanResponsePlan = { [key: string]: unknown };

export interface UserPlanResponse {
  /** User ID */
  id?: string;
  /** User email */
  email?: string;
  /** Current plan details */
  plan?: UserPlanResponsePlan;
  /** Number of validations used this month */
  monthlyValidationsUsed?: number;
  /** Subscription status */
  subscriptionStatus?: string;
  /**
   * Trial end date if applicable
   * @nullable
   */
  trialEndDate?: string | null;
  /** Number of projects */
  projectsCount?: number;
}

export type ErrorError = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export interface Error {
  error?: ErrorError;
  /** Request identifier */
  request_id?: string;
}

export type UnauthorizedErrorErrorCode = typeof UnauthorizedErrorErrorCode[keyof typeof UnauthorizedErrorErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnauthorizedErrorErrorCode = {
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export type UnauthorizedErrorError = {
  code?: UnauthorizedErrorErrorCode;
  /** Error message */
  message?: string;
};

export interface UnauthorizedError {
  error?: UnauthorizedErrorError;
}

export type ValidationErrorErrorCode = typeof ValidationErrorErrorCode[keyof typeof ValidationErrorErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ValidationErrorErrorCode = {
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_PLAN: 'INVALID_PLAN',
} as const;

export type ValidationErrorError = {
  code?: ValidationErrorErrorCode;
  /** Error message */
  message?: string;
};

export interface ValidationError {
  error?: ValidationErrorError;
}

export type NotFoundErrorErrorCode = typeof NotFoundErrorErrorCode[keyof typeof NotFoundErrorErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotFoundErrorErrorCode = {
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type NotFoundErrorError = {
  code?: NotFoundErrorErrorCode;
  /** Error message */
  message?: string;
};

export interface NotFoundError {
  error?: NotFoundErrorError;
}

export type LimitExceededErrorCode = typeof LimitExceededErrorCode[keyof typeof LimitExceededErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LimitExceededErrorCode = {
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
} as const;

export interface LimitExceededError {
  code?: LimitExceededErrorCode;
  /** Error message */
  message?: string;
}

export type ServerErrorErrorCode = typeof ServerErrorErrorCode[keyof typeof ServerErrorErrorCode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServerErrorErrorCode = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ServerErrorError = {
  code?: ServerErrorErrorCode;
  /** Error message */
  message?: string;
};

export interface ServerError {
  error?: ServerErrorError;
}

/**
 * API key status
 */
export type ApiKeyStatus = typeof ApiKeyStatus[keyof typeof ApiKeyStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApiKeyStatus = {
  active: 'active',
  revoked: 'revoked',
} as const;

export interface ApiKey {
  /** API key ID */
  id?: string;
  /** API key prefix (first 6 characters) */
  prefix?: string;
  /** API key status */
  status?: ApiKeyStatus;
  /** Creation timestamp */
  created_at?: string;
  /**
   * Last used timestamp
   * @nullable
   */
  last_used_at?: string | null;
}

/**
 * Webhook status
 */
export type WebhookStatus = typeof WebhookStatus[keyof typeof WebhookStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WebhookStatus = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;

export interface Webhook {
  /** Webhook ID */
  id?: string;
  /** Webhook URL */
  url?: string;
  /** Events this webhook is subscribed to */
  events?: string[];
  /** Webhook status */
  status?: WebhookStatus;
  /** Creation timestamp */
  created_at?: string;
  /**
   * Last time webhook was fired
   * @nullable
   */
  last_fired_at?: string | null;
}

export interface Address {
  /** Street address line 1 */
  line1?: string;
  /** Street address line 2 */
  line2?: string;
  /** City */
  city?: string;
  /** State or province */
  state?: string;
  /** Postal code */
  postal_code?: string;
  /** Two-letter country code */
  country?: string;
  /**
   * Latitude
   * @nullable
   */
  lat?: number | null;
  /**
   * Longitude
   * @nullable
   */
  lng?: number | null;
}

export interface Customer {
  /** Customer email */
  email?: string;
  /** Customer phone */
  phone?: string;
  /** Customer first name */
  first_name?: string;
  /** Customer last name */
  last_name?: string;
}

/**
 * Type of match
 */
export type CustomerMatchMatchType = typeof CustomerMatchMatchType[keyof typeof CustomerMatchMatchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomerMatchMatchType = {
  exact_email: 'exact_email',
  exact_phone: 'exact_phone',
  fuzzy_name: 'fuzzy_name',
} as const;

export interface CustomerMatch {
  /** Customer ID */
  id?: string;
  /** Similarity score (0-1) */
  similarity_score?: number;
  /** Type of match */
  match_type?: CustomerMatchMatchType;
  data?: Customer;
}

/**
 * Type of match
 */
export type AddressMatchMatchType = typeof AddressMatchMatchType[keyof typeof AddressMatchMatchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddressMatchMatchType = {
  exact_address: 'exact_address',
  exact_postal: 'exact_postal',
  fuzzy_address: 'fuzzy_address',
} as const;

export interface AddressMatch {
  /** Address ID */
  id?: string;
  /** Similarity score (0-1) */
  similarity_score?: number;
  /** Type of match */
  match_type?: AddressMatchMatchType;
  data?: Address;
}

export type DedupeResultMatchesItemData = { [key: string]: unknown };

export type DedupeResultMatchesItem = {
  id?: string;
  similarity_score?: number;
  match_type?: string;
  data?: DedupeResultMatchesItemData;
};

export type DedupeResultSuggestedAction = typeof DedupeResultSuggestedAction[keyof typeof DedupeResultSuggestedAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedupeResultSuggestedAction = {
  create_new: 'create_new',
  merge_with: 'merge_with',
  review: 'review',
} as const;

export interface DedupeResult {
  matches?: DedupeResultMatchesItem[];
  suggested_action?: DedupeResultSuggestedAction;
  /** @nullable */
  canonical_id?: string | null;
}

export interface ValidationResult {
  /** Whether the validation passed */
  valid?: boolean;
  /** List of reason codes */
  reason_codes?: string[];
  /** Whether the result is disposable (for email) */
  disposable?: boolean;
}

export interface AddressValidationResult {
  /** Whether the address is valid */
  valid?: boolean;
  /** List of reason codes */
  reason_codes?: string[];
  /** Whether the address is a P.O. Box */
  po_box?: boolean;
  /** Whether postal code matches city */
  postal_city_match?: boolean;
  /** Whether the address is within bounds */
  in_bounds?: boolean;
}

/**
 * Additional metadata
 */
export type LogEntryMeta = { [key: string]: unknown };

export interface LogEntry {
  /** Log entry ID */
  id?: string;
  /** Log entry type */
  type?: string;
  /** API endpoint */
  endpoint?: string;
  /** List of reason codes */
  reason_codes?: string[];
  /** HTTP status code */
  status?: number;
  /** Additional metadata */
  meta?: LogEntryMeta;
  /** Creation timestamp */
  created_at?: string;
}

export interface Rule {
  /** Rule ID */
  id?: string;
  /** Rule name */
  name?: string;
  /** Rule description */
  description?: string;
  /** Rule category */
  category?: string;
  /** Whether the rule is enabled */
  enabled?: boolean;
}

/**
 * Severity level
 */
export type ReasonCodeSeverity = typeof ReasonCodeSeverity[keyof typeof ReasonCodeSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReasonCodeSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface ReasonCode {
  /** Reason code */
  code?: string;
  /** Description of the reason code */
  description?: string;
  /** Category of the reason code */
  category?: string;
  /** Severity level */
  severity?: ReasonCodeSeverity;
}

/**
 * Severity level
 */
export type ErrorCodeSeverity = typeof ErrorCodeSeverity[keyof typeof ErrorCodeSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCodeSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface ErrorCode {
  /** Error code */
  code?: string;
  /** Description of the error code */
  description?: string;
  /** Category of the error code */
  category?: string;
  /** Severity level */
  severity?: ErrorCodeSeverity;
}

/**
 * Severity level
 */
export type CustomRuleSeverity = typeof CustomRuleSeverity[keyof typeof CustomRuleSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CustomRuleSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface CustomRule {
  /** Rule ID */
  id?: string;
  /** Rule name */
  name?: string;
  /** Rule description */
  description?: string;
  /** Reason code to trigger */
  reason_code?: string;
  /** Severity level */
  severity?: CustomRuleSeverity;
  /** Whether the rule is enabled */
  enabled?: boolean;
}

export type GetUserProjects200ProjectsItem = {
  /** Project ID */
  id?: string;
  /** Project name */
  name?: string;
  /** Project creation timestamp */
  created_at?: string;
};

export type GetUserProjects200Plan = {
  /** Plan slug */
  slug?: string;
  /** Maximum number of projects allowed */
  projectsLimit?: number;
  /** Current number of projects */
  currentProjects?: number;
  /** Whether user can create more projects */
  canCreateMore?: boolean;
};

export type GetUserProjects200 = {
  projects?: GetUserProjects200ProjectsItem[];
  plan?: GetUserProjects200Plan;
};

export type CreateProjectBody = {
  /** Project name */
  name: string;
};

export type CreateProject201 = {
  /** Project ID */
  id?: string;
  /** Project name */
  name?: string;
  /** Project creation timestamp */
  created_at?: string;
};

export type CreateProject402Plan = {
  slug?: string;
  projectsLimit?: number;
  currentProjects?: number;
};

export type CreateProject402 = {
  error?: LimitExceededError;
  plan?: CreateProject402Plan;
};

export type DeleteProject200 = {
  /** Success message */
  message?: string;
};

/**
 * Plan slug to update to
 */
export type UpdateUserPlanBodyPlanSlug = typeof UpdateUserPlanBodyPlanSlug[keyof typeof UpdateUserPlanBodyPlanSlug];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserPlanBodyPlanSlug = {
  free: 'free',
  starter: 'starter',
  growth: 'growth',
  scale: 'scale',
  enterprise: 'enterprise',
} as const;

export type UpdateUserPlanBody = {
  /** Plan slug to update to */
  planSlug: UpdateUserPlanBodyPlanSlug;
  /**
   * Days for trial period (optional)
   * @minimum 1
   * @maximum 30
   * @nullable
   */
  trialDays?: number | null;
};

/**
 * Plan features
 */
export type GetAvailablePlans200ItemFeatures = { [key: string]: unknown };

export type GetAvailablePlans200Item = {
  /** Plan ID */
  id?: string;
  /** Plan name */
  name?: string;
  /** Plan slug */
  slug?: string;
  /** Plan price */
  price?: number;
  /** Monthly validation limit */
  validationsLimit?: number;
  /** Project limit */
  projectsLimit?: number;
  /** Log retention days */
  logsRetentionDays?: number;
  /** Plan features */
  features?: GetAvailablePlans200ItemFeatures;
  /** Overage rate per validation */
  overageRate?: number;
  /**
   * Maximum overage allowed
   * @nullable
   */
  maxOverage?: number | null;
  /**
   * SLA percentage
   * @nullable
   */
  sla?: string | null;
  /** Whether this is a custom plan */
  isCustom?: boolean;
  /** Plan creation timestamp */
  createdAt?: string;
  /** Plan update timestamp */
  updatedAt?: string;
};

export type CheckValidationLimitsBody = {
  /**
   * Number of validations to check
   * @minimum 1
   */
  count: number;
};

export type CheckValidationLimits200 = {
  /** Whether the user can proceed with the requested validations */
  canProceed?: boolean;
  /** Remaining validations in current period */
  remainingValidations?: number;
  /** Whether overage is allowed on current plan */
  overageAllowed?: boolean;
  /** Validations used this month */
  monthlyValidationsUsed?: number;
  /** Plan validation limit */
  planValidationsLimit?: number;
};

export type RegisterUserBody = {
  /** User email address */
  email: string;
  /**
   * User password (minimum 8 characters)
   * @minLength 8
   */
  password: string;
  /**
   * Confirm password (must match password)
   * @minLength 8
   */
  confirm_password: string;
};

export type RegisterUser201User = {
  /** User ID */
  id?: string;
  /** User email */
  email?: string;
};

export type RegisterUser201 = {
  /** JWT authentication token */
  token?: string;
  user?: RegisterUser201User;
  /** Request identifier */
  request_id?: string;
};

export type LoginUserBody = {
  /** User email address */
  email: string;
  /** User password */
  password: string;
};

export type LoginUser200User = {
  /** User ID */
  id?: string;
  /** User email */
  email?: string;
};

export type LoginUser200 = {
  /** JWT authentication token */
  token?: string;
  user?: LoginUser200User;
  /** Request identifier */
  request_id?: string;
};

export type LogoutUser200 = {
  /** Success message */
  message?: string;
};

export type ListApiKeys200 = {
  data?: ApiKey[];
  request_id?: string;
};

export type CreateApiKeyBody = {
  /** Optional name for the API key */
  name?: string;
};

export type CreateApiKey201 = {
  /** API key ID */
  id?: string;
  /** API key prefix (first 6 characters) */
  prefix?: string;
  /** The full API key (shown only once) */
  full_key?: string;
  /** API key status */
  status?: string;
  /** Creation timestamp */
  created_at?: string;
  request_id?: string;
};

export type RevokeApiKey200 = {
  /** API key ID */
  id?: string;
  /** API key status */
  status?: string;
  request_id?: string;
};

export type ListWebhooks200DataItemStatus = typeof ListWebhooks200DataItemStatus[keyof typeof ListWebhooks200DataItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListWebhooks200DataItemStatus = {
  active: 'active',
  inactive: 'inactive',
  deleted: 'deleted',
} as const;

export type ListWebhooks200DataItem = {
  id?: string;
  url?: string;
  events?: string[];
  status?: ListWebhooks200DataItemStatus;
  created_at?: string;
  /** @nullable */
  last_fired_at?: string | null;
};

export type ListWebhooks200 = {
  data?: ListWebhooks200DataItem[];
  request_id?: string;
};

export type CreateWebhookBody = {
  /** The webhook URL to send events to */
  url: string;
  /** Events to subscribe to */
  events: string[];
};

export type CreateWebhook201 = {
  id?: string;
  url?: string;
  events?: string[];
  secret?: string;
  status?: string;
  created_at?: string;
  request_id?: string;
};

export type DeleteWebhook200 = {
  id?: string;
  status?: string;
  request_id?: string;
};

/**
 * Type of sample payload to send
 */
export type TestWebhookBodyPayloadType = typeof TestWebhookBodyPayloadType[keyof typeof TestWebhookBodyPayloadType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestWebhookBodyPayloadType = {
  validation: 'validation',
  order: 'order',
  custom: 'custom',
} as const;

/**
 * Custom payload if payload_type is "custom"
 */
export type TestWebhookBodyCustomPayload = { [key: string]: unknown };

export type TestWebhookBody = {
  /** The webhook URL to send the payload to */
  url: string;
  /** Type of sample payload to send */
  payload_type: TestWebhookBodyPayloadType;
  /** Custom payload if payload_type is "custom" */
  custom_payload?: TestWebhookBodyCustomPayload;
};

export type TestWebhook200Payload = { [key: string]: unknown };

export type TestWebhook200ResponseHeaders = { [key: string]: unknown };

export type TestWebhook200Response = {
  status?: number;
  status_text?: string;
  headers?: TestWebhook200ResponseHeaders;
  body?: string;
};

export type TestWebhook200 = {
  sent_to?: string;
  payload?: TestWebhook200Payload;
  response?: TestWebhook200Response;
  request_id?: string;
};

/**
 * Rule severity level
 */
export type GetAvailableRules200RulesItemSeverity = typeof GetAvailableRules200RulesItemSeverity[keyof typeof GetAvailableRules200RulesItemSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAvailableRules200RulesItemSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;

/**
 * Rule configuration options
 */
export type GetAvailableRules200RulesItemConfig = { [key: string]: unknown };

export type GetAvailableRules200RulesItem = {
  /** Rule identifier */
  id?: string;
  /** Human-readable rule name */
  name?: string;
  /** Rule description */
  description?: string;
  /** Rule category */
  category?: string;
  /** Rule severity level */
  severity?: GetAvailableRules200RulesItemSeverity;
  /** Whether the rule is enabled */
  enabled?: boolean;
  /** Rule configuration options */
  config?: GetAvailableRules200RulesItemConfig;
  /** Rule condition expression */
  condition?: string;
};

export type GetAvailableRules200 = {
  rules?: GetAvailableRules200RulesItem[];
  request_id?: string;
};

export type GetErrorCodeCatalog200ErrorCodesItem = {
  /** Error code */
  code?: string;
  /** Error description */
  description?: string;
  /** Error category */
  category?: string;
};

export type GetErrorCodeCatalog200 = {
  error_codes?: GetErrorCodeCatalog200ErrorCodesItem[];
  request_id?: string;
};

/**
 * Reason severity
 */
export type GetReasonCodeCatalog200ReasonCodesItemSeverity = typeof GetReasonCodeCatalog200ReasonCodesItemSeverity[keyof typeof GetReasonCodeCatalog200ReasonCodesItemSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetReasonCodeCatalog200ReasonCodesItemSeverity = {
  info: 'info',
  warning: 'warning',
  error: 'error',
} as const;

export type GetReasonCodeCatalog200ReasonCodesItem = {
  /** Reason code */
  code?: string;
  /** Reason description */
  description?: string;
  /** Reason category */
  category?: string;
  /** Reason severity */
  severity?: GetReasonCodeCatalog200ReasonCodesItemSeverity;
};

export type GetReasonCodeCatalog200 = {
  reason_codes?: GetReasonCodeCatalog200ReasonCodesItem[];
  request_id?: string;
};

/**
 * Sample payload to test rules against
 */
export type TestRulesAgainstPayloadBodyPayload = { [key: string]: unknown };

export type TestRulesAgainstPayloadBody = {
  /** Sample payload to test rules against */
  payload: TestRulesAgainstPayloadBodyPayload;
  /** Optional list of specific rule IDs to test */
  rule_ids?: string[];
};

/**
 * Rule severity
 */
export type TestRulesAgainstPayload200TriggeredRulesItemSeverity = typeof TestRulesAgainstPayload200TriggeredRulesItemSeverity[keyof typeof TestRulesAgainstPayload200TriggeredRulesItemSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestRulesAgainstPayload200TriggeredRulesItemSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;

export type TestRulesAgainstPayload200TriggeredRulesItem = {
  /** ID of triggered rule */
  rule_id?: string;
  /** Name of triggered rule */
  rule_name?: string;
  /** Rule severity */
  severity?: TestRulesAgainstPayload200TriggeredRulesItemSeverity;
  /** Reason codes generated */
  reason_codes?: string[];
};

export type TestRulesAgainstPayload200 = {
  triggered_rules?: TestRulesAgainstPayload200TriggeredRulesItem[];
  request_id?: string;
};

/**
 * A structured JSON object defining the rule's logic.
 */
export type RegisterCustomRulesBodyRulesItemConditions = { [key: string]: unknown };

/**
 * Rule severity
 */
export type RegisterCustomRulesBodyRulesItemSeverity = typeof RegisterCustomRulesBodyRulesItemSeverity[keyof typeof RegisterCustomRulesBodyRulesItemSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterCustomRulesBodyRulesItemSeverity = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;

export type RegisterCustomRulesBodyRulesItem = (unknown & {
  /** Custom rule name */
  name: string;
  /** Rule description */
  description?: string;
  /** A string containing the rule's logic expression. */
  condition?: string;
  /** A structured JSON object defining the rule's logic. */
  conditions?: RegisterCustomRulesBodyRulesItemConditions;
  /** Rule severity */
  severity?: RegisterCustomRulesBodyRulesItemSeverity;
  /** Whether the rule is enabled */
  enabled?: boolean;
}) | (unknown & {
  /** Custom rule name */
  name: string;
  /** Rule description */
  description?: string;
  /** A string containing the rule's logic expression. */
  condition?: string;
  /** A structured JSON object defining the rule's logic. */
  conditions?: RegisterCustomRulesBodyRulesItemConditions;
  /** Rule severity */
  severity?: RegisterCustomRulesBodyRulesItemSeverity;
  /** Whether the rule is enabled */
  enabled?: boolean;
});

export type RegisterCustomRulesBody = {
  /** Array of custom rules to register */
  rules: RegisterCustomRulesBodyRulesItem[];
};

export type RegisterCustomRules201RegisteredRulesItem = {
  /** Registered rule ID */
  id?: string;
  /** Rule name */
  name?: string;
  /** Registration status */
  status?: string;
};

export type RegisterCustomRules201 = {
  registered_rules?: RegisterCustomRules201RegisteredRulesItem[];
  request_id?: string;
};

export type DeleteCustomRule200 = {
  /** Deleted rule ID */
  id?: string;
  request_id?: string;
};

export type GetLogsParams = {
/**
 * Filter by exact reason code
 */
reason_code?: string;
/**
 * Filter by exact endpoint
 */
endpoint?: string;
/**
 * Filter by HTTP status code
 */
status?: number;
/**
 * Number of logs to return
 * @maximum 1000
 */
limit?: number;
/**
 * Number of logs to skip
 */
offset?: number;
};

export type GetLogs200 = {
  data?: LogEntry[];
  /**
   * Next offset for pagination
   * @nullable
   */
  next_cursor?: string | null;
  /** Total number of matching logs */
  total_count?: number;
  request_id?: string;
};

/**
 * Environment
 */
export type ListPersonalAccessTokens200DataItemEnv = typeof ListPersonalAccessTokens200DataItemEnv[keyof typeof ListPersonalAccessTokens200DataItemEnv];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ListPersonalAccessTokens200DataItemEnv = {
  test: 'test',
  live: 'live',
} as const;

export type ListPersonalAccessTokens200DataItem = {
  /** Token ID */
  id?: string;
  /** Public token identifier (last 4 chars shown) */
  token_id?: string;
  /** Token name */
  name?: string;
  /** Access scopes */
  scopes?: string[];
  /** Environment */
  env?: ListPersonalAccessTokens200DataItemEnv;
  /**
   * Last usage timestamp
   * @nullable
   */
  last_used_at?: string | null;
  /**
   * Last usage IP
   * @nullable
   */
  last_used_ip?: string | null;
  /**
   * Expiration date
   * @nullable
   */
  expires_at?: string | null;
  /** Whether token is disabled */
  disabled?: boolean;
  /** Creation timestamp */
  created_at?: string;
};

export type ListPersonalAccessTokens200 = {
  data?: ListPersonalAccessTokens200DataItem[];
  request_id?: string;
};

export type CreatePersonalAccessTokenBodyScopesItem = typeof CreatePersonalAccessTokenBodyScopesItem[keyof typeof CreatePersonalAccessTokenBodyScopesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePersonalAccessTokenBodyScopesItem = {
  'keys:read': 'keys:read',
  'keys:write': 'keys:write',
  'logs:read': 'logs:read',
  'usage:read': 'usage:read',
  'webhooks:manage': 'webhooks:manage',
  'connectors:manage': 'connectors:manage',
  'pats:manage': 'pats:manage',
  'projects:manage': 'projects:manage',
  'rules:manage': 'rules:manage',
} as const;

/**
 * Environment for the token
 */
export type CreatePersonalAccessTokenBodyEnv = typeof CreatePersonalAccessTokenBodyEnv[keyof typeof CreatePersonalAccessTokenBodyEnv];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePersonalAccessTokenBodyEnv = {
  test: 'test',
  live: 'live',
} as const;

export type CreatePersonalAccessTokenBody = {
  /** Token name */
  name: string;
  /** Access scopes for the token */
  scopes: CreatePersonalAccessTokenBodyScopesItem[];
  /** Environment for the token */
  env?: CreatePersonalAccessTokenBodyEnv;
  /** Optional expiration date */
  expires_at?: string;
  /** Optional IP allowlist (CIDR notation) */
  ip_allowlist?: string[];
  /** Optional project restriction */
  project_id?: string;
};

export type CreatePersonalAccessToken201 = {
  /** The full PAT (shown only once) */
  token?: string;
  /** Token identifier */
  token_id?: string;
  name?: string;
  scopes?: string[];
  env?: string;
  /** @nullable */
  expires_at?: string | null;
  created_at?: string;
  request_id?: string;
};

export type RevokePersonalAccessToken200 = {
  /** Token ID */
  id?: string;
  /** Token identifier */
  token_id?: string;
  /** Whether token is disabled */
  disabled?: boolean;
  request_id?: string;
};

export type GetUsage200Totals = {
  /** Total validations */
  validations?: number;
  /** Total orders */
  orders?: number;
};

export type GetUsage200ByDayItem = {
  /** Date */
  date?: string;
  /** Validations for this day */
  validations?: number;
  /** Orders for this day */
  orders?: number;
};

export type GetUsage200TopReasonCodesItem = {
  /** Reason code */
  code?: string;
  /** Count */
  count?: number;
};

export type GetUsage200 = {
  /** Time period */
  period?: string;
  totals?: GetUsage200Totals;
  by_day?: GetUsage200ByDayItem[];
  top_reason_codes?: GetUsage200TopReasonCodesItem[];
  /** Cache hit ratio percentage */
  cache_hit_ratio?: number;
  request_id?: string;
};

/**
 * Country-specific default settings
 */
export type GetSettings200CountryDefaults = { [key: string]: unknown };

/**
 * Formatting preferences
 */
export type GetSettings200Formatting = { [key: string]: unknown };

/**
 * Risk assessment thresholds
 */
export type GetSettings200RiskThresholds = { [key: string]: unknown };

export type GetSettings200 = {
  /** Country-specific default settings */
  country_defaults?: GetSettings200CountryDefaults;
  /** Formatting preferences */
  formatting?: GetSettings200Formatting;
  /** Risk assessment thresholds */
  risk_thresholds?: GetSettings200RiskThresholds;
  /** Request identifier */
  request_id?: string;
};

/**
 * Country-specific default settings
 */
export type UpdateSettingsBodyCountryDefaults = { [key: string]: unknown };

/**
 * Formatting preferences
 */
export type UpdateSettingsBodyFormatting = { [key: string]: unknown };

/**
 * Risk assessment thresholds
 */
export type UpdateSettingsBodyRiskThresholds = { [key: string]: unknown };

export type UpdateSettingsBody = {
  /** Country-specific default settings */
  country_defaults?: UpdateSettingsBodyCountryDefaults;
  /** Formatting preferences */
  formatting?: UpdateSettingsBodyFormatting;
  /** Risk assessment thresholds */
  risk_thresholds?: UpdateSettingsBodyRiskThresholds;
};

export type UpdateSettings200 = {
  /** Success message */
  message?: string;
  /** Request identifier */
  request_id?: string;
};

/**
 * Reason for data erasure (gdpr/ccpa)
 */
export type EraseDataBodyReason = typeof EraseDataBodyReason[keyof typeof EraseDataBodyReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EraseDataBodyReason = {
  gdpr: 'gdpr',
  ccpa: 'ccpa',
} as const;

export type EraseDataBody = {
  /** Reason for data erasure (gdpr/ccpa) */
  reason: EraseDataBodyReason;
};

export type EraseData202 = {
  /** Confirmation message */
  message?: string;
  /** Request identifier */
  request_id?: string;
};

export type CreateCheckoutSession200 = {
  session_url?: string;
  session_id?: string;
  request_id?: string;
};

export type CreateCustomerPortalSession200 = {
  portal_url?: string;
  request_id?: string;
};

export type DeleteLog200 = {
  /** Success message */
  message?: string;
  /** Request identifier */
  request_id?: string;
};

export type NormalizeAddressBodyAddress = {
  line1: string;
  line2?: string;
  city: string;
  state?: string;
  postal_code: string;
  /**
   * @minLength 2
   * @maxLength 2
   */
  country: string;
};

export type NormalizeAddressBody = {
  address: NormalizeAddressBodyAddress;
};

export type NormalizeAddress200Normalized = {
  line1?: string;
  line2?: string;
  city?: string;
  state?: string;
  postal_code?: string;
  country?: string;
};

export type NormalizeAddress200 = {
  normalized?: NormalizeAddress200Normalized;
  request_id?: string;
};

export type NormalizeAddress400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type NormalizeAddress400 = {
  error?: NormalizeAddress400Error;
  /** Request identifier */
  request_id?: string;
};

export type NormalizeAddress401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type NormalizeAddress401 = {
  error?: NormalizeAddress401Error;
  /** Request identifier */
  request_id?: string;
};

export type NormalizeAddress429Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type NormalizeAddress429 = {
  error?: NormalizeAddress429Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * The type of data to validate
 */
export type BatchValidateBodyType = typeof BatchValidateBodyType[keyof typeof BatchValidateBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchValidateBodyType = {
  email: 'email',
  phone: 'phone',
  address: 'address',
  'tax-id': 'tax-id',
} as const;

/**
 * Data items to validate (format depends on type)
 */
export type BatchValidateBodyDataItem = { [key: string]: unknown };

export type BatchValidateBody = {
  /** The type of data to validate */
  type: BatchValidateBodyType;
  /**
   * Array of items to validate
   * @maxItems 10000
   */
  data: BatchValidateBodyDataItem[];
};

/**
 * Job status
 */
export type BatchValidate202Status = typeof BatchValidate202Status[keyof typeof BatchValidate202Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchValidate202Status = {
  pending: 'pending',
} as const;

export type BatchValidate202 = {
  /** Unique job identifier */
  job_id?: string;
  /** Job status */
  status?: BatchValidate202Status;
  /** Request identifier */
  request_id?: string;
};

export type BatchValidate400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type BatchValidate400 = {
  error?: BatchValidate400Error;
  /** Request identifier */
  request_id?: string;
};

export type BatchValidate401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type BatchValidate401 = {
  error?: BatchValidate401Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * The type of data to deduplicate
 */
export type BatchDedupeBodyType = typeof BatchDedupeBodyType[keyof typeof BatchDedupeBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchDedupeBodyType = {
  customers: 'customers',
  addresses: 'addresses',
} as const;

/**
 * Data items to deduplicate (format depends on type)
 */
export type BatchDedupeBodyDataItem = { [key: string]: unknown };

export type BatchDedupeBody = {
  /** The type of data to deduplicate */
  type: BatchDedupeBodyType;
  /**
   * Array of items to deduplicate
   * @maxItems 10000
   */
  data: BatchDedupeBodyDataItem[];
};

/**
 * Job status
 */
export type BatchDedupe202Status = typeof BatchDedupe202Status[keyof typeof BatchDedupe202Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BatchDedupe202Status = {
  pending: 'pending',
} as const;

export type BatchDedupe202 = {
  /** Unique job identifier */
  job_id?: string;
  /** Job status */
  status?: BatchDedupe202Status;
  /** Request identifier */
  request_id?: string;
};

export type BatchDedupe400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type BatchDedupe400 = {
  error?: BatchDedupe400Error;
  /** Request identifier */
  request_id?: string;
};

export type BatchDedupe401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type BatchDedupe401 = {
  error?: BatchDedupe401Error;
  /** Request identifier */
  request_id?: string;
};

export type DedupeCustomerBody = {
  /** Customer email */
  email: string;
  /** Customer phone */
  phone?: string;
  /** Customer first name */
  first_name: string;
  /** Customer last name */
  last_name: string;
};

/**
 * Type of match
 */
export type DedupeCustomer200MatchesItemMatchType = typeof DedupeCustomer200MatchesItemMatchType[keyof typeof DedupeCustomer200MatchesItemMatchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedupeCustomer200MatchesItemMatchType = {
  exact_email: 'exact_email',
  exact_phone: 'exact_phone',
  fuzzy_name: 'fuzzy_name',
} as const;

export type DedupeCustomer200MatchesItemData = {
  /** Customer email */
  email?: string;
  /** Customer phone */
  phone?: string;
  /** Customer first name */
  first_name?: string;
  /** Customer last name */
  last_name?: string;
};

export type DedupeCustomer200MatchesItem = {
  /** Customer ID */
  id?: string;
  /** Similarity score (0-1) */
  similarity_score?: number;
  /** Type of match */
  match_type?: DedupeCustomer200MatchesItemMatchType;
  data?: DedupeCustomer200MatchesItemData;
};

/**
 * Suggested action
 */
export type DedupeCustomer200SuggestedAction = typeof DedupeCustomer200SuggestedAction[keyof typeof DedupeCustomer200SuggestedAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedupeCustomer200SuggestedAction = {
  create_new: 'create_new',
  merge_with: 'merge_with',
  review: 'review',
} as const;

export type DedupeCustomer200 = {
  matches?: DedupeCustomer200MatchesItem[];
  /** Suggested action */
  suggested_action?: DedupeCustomer200SuggestedAction;
  /**
   * Suggested canonical ID
   * @nullable
   */
  canonical_id?: string | null;
  request_id?: string;
};

export type DedupeCustomer400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type DedupeCustomer400 = {
  error?: DedupeCustomer400Error;
  /** Request identifier */
  request_id?: string;
};

export type DedupeAddressBody = {
  /** Street address line 1 */
  line1: string;
  /** Street address line 2 */
  line2?: string;
  /** City */
  city: string;
  /** State or province */
  state?: string;
  /** Postal code */
  postal_code: string;
  /**
   * Two-letter country code
   * @minLength 2
   * @maxLength 2
   */
  country: string;
};

/**
 * Type of match
 */
export type DedupeAddress200MatchesItemMatchType = typeof DedupeAddress200MatchesItemMatchType[keyof typeof DedupeAddress200MatchesItemMatchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedupeAddress200MatchesItemMatchType = {
  exact_address: 'exact_address',
  exact_postal: 'exact_postal',
  fuzzy_address: 'fuzzy_address',
} as const;

export type DedupeAddress200MatchesItemData = {
  /** Street address line 1 */
  line1?: string;
  /** Street address line 2 */
  line2?: string;
  /** City */
  city?: string;
  /** State or province */
  state?: string;
  /** Postal code */
  postal_code?: string;
  /** Two-letter country code */
  country?: string;
  /**
   * Latitude
   * @nullable
   */
  lat?: number | null;
  /**
   * Longitude
   * @nullable
   */
  lng?: number | null;
};

export type DedupeAddress200MatchesItem = {
  /** Address ID */
  id?: string;
  /** Similarity score (0-1) */
  similarity_score?: number;
  /** Type of match */
  match_type?: DedupeAddress200MatchesItemMatchType;
  data?: DedupeAddress200MatchesItemData;
};

/**
 * Suggested action
 */
export type DedupeAddress200SuggestedAction = typeof DedupeAddress200SuggestedAction[keyof typeof DedupeAddress200SuggestedAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DedupeAddress200SuggestedAction = {
  create_new: 'create_new',
  merge_with: 'merge_with',
  review: 'review',
} as const;

export type DedupeAddress200 = {
  matches?: DedupeAddress200MatchesItem[];
  /** Suggested action */
  suggested_action?: DedupeAddress200SuggestedAction;
  /**
   * Suggested canonical ID
   * @nullable
   */
  canonical_id?: string | null;
  request_id?: string;
};

export type DedupeAddress400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type DedupeAddress400 = {
  error?: DedupeAddress400Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * Type of records to merge
 */
export type MergeDeduplicatedBodyType = typeof MergeDeduplicatedBodyType[keyof typeof MergeDeduplicatedBodyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MergeDeduplicatedBodyType = {
  customer: 'customer',
  address: 'address',
} as const;

export type MergeDeduplicatedBody = {
  /** Type of records to merge */
  type: MergeDeduplicatedBodyType;
  /** IDs to merge */
  ids: string[];
  /** ID of canonical record to keep */
  canonical_id: string;
};

export type MergeDeduplicated200 = {
  /** Whether merge was successful */
  success?: boolean;
  /** Number of records merged */
  merged_count?: number;
  /** ID of canonical record */
  canonical_id?: string;
  request_id?: string;
};

export type MergeDeduplicated400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type MergeDeduplicated400 = {
  error?: MergeDeduplicated400Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * Current job status
 */
export type GetJobStatusById200Status = typeof GetJobStatusById200Status[keyof typeof GetJobStatusById200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetJobStatusById200Status = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * Job result data
 * @nullable
 */
export type GetJobStatusById200Result = { [key: string]: unknown } | null;

export type GetJobStatusById200 = {
  /** Job ID */
  id?: string;
  /** Current job status */
  status?: GetJobStatusById200Status;
  /**
   * Job completion percentage
   * @minimum 0
   * @maximum 100
   */
  progress?: number;
  /**
   * Job result data
   * @nullable
   */
  result?: GetJobStatusById200Result;
  /**
   * Error message if job failed
   * @nullable
   */
  error?: string | null;
  /** Job creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
  request_id?: string;
};

export type GetJobStatusById404Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type GetJobStatusById404 = {
  error?: GetJobStatusById404Error;
  /** Request identifier */
  request_id?: string;
};

export type EvaluateOrderBodyCustomer = {
  /** Customer email */
  email?: string;
  /** Customer phone */
  phone?: string;
  /** Customer first name */
  first_name?: string;
  /** Customer last name */
  last_name?: string;
};

export type EvaluateOrderBodyShippingAddress = {
  /** Street address line 1 */
  line1?: string;
  /** Street address line 2 */
  line2?: string;
  /** City */
  city?: string;
  /** State or province */
  state?: string;
  /** Postal code */
  postal_code?: string;
  /** Two-letter country code */
  country?: string;
  /**
   * Latitude
   * @nullable
   */
  lat?: number | null;
  /**
   * Longitude
   * @nullable
   */
  lng?: number | null;
};

/**
 * Payment method
 */
export type EvaluateOrderBodyPaymentMethod = typeof EvaluateOrderBodyPaymentMethod[keyof typeof EvaluateOrderBodyPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluateOrderBodyPaymentMethod = {
  card: 'card',
  cod: 'cod',
  bank_transfer: 'bank_transfer',
} as const;

export type EvaluateOrderBody = {
  /** Unique order identifier */
  order_id: string;
  customer: EvaluateOrderBodyCustomer;
  shipping_address: EvaluateOrderBodyShippingAddress;
  /** Order total amount */
  total_amount: number;
  /**
   * Currency code (e.g., USD, EUR)
   * @pattern ^[A-Z]{3}$
   */
  currency: string;
  /** Payment method */
  payment_method?: EvaluateOrderBodyPaymentMethod;
};

/**
 * Recommended action
 */
export type EvaluateOrder200Action = typeof EvaluateOrder200Action[keyof typeof EvaluateOrder200Action];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluateOrder200Action = {
  approve: 'approve',
  hold: 'hold',
  block: 'block',
} as const;

export type EvaluateOrder200CustomerDedupeMatchesItemData = { [key: string]: unknown };

export type EvaluateOrder200CustomerDedupeMatchesItem = {
  id?: string;
  similarity_score?: number;
  match_type?: string;
  data?: EvaluateOrder200CustomerDedupeMatchesItemData;
};

export type EvaluateOrder200CustomerDedupeSuggestedAction = typeof EvaluateOrder200CustomerDedupeSuggestedAction[keyof typeof EvaluateOrder200CustomerDedupeSuggestedAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluateOrder200CustomerDedupeSuggestedAction = {
  create_new: 'create_new',
  merge_with: 'merge_with',
  review: 'review',
} as const;

export type EvaluateOrder200CustomerDedupe = {
  matches?: EvaluateOrder200CustomerDedupeMatchesItem[];
  suggested_action?: EvaluateOrder200CustomerDedupeSuggestedAction;
  /** @nullable */
  canonical_id?: string | null;
};

export type EvaluateOrder200AddressDedupeMatchesItemData = { [key: string]: unknown };

export type EvaluateOrder200AddressDedupeMatchesItem = {
  id?: string;
  similarity_score?: number;
  match_type?: string;
  data?: EvaluateOrder200AddressDedupeMatchesItemData;
};

export type EvaluateOrder200AddressDedupeSuggestedAction = typeof EvaluateOrder200AddressDedupeSuggestedAction[keyof typeof EvaluateOrder200AddressDedupeSuggestedAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EvaluateOrder200AddressDedupeSuggestedAction = {
  create_new: 'create_new',
  merge_with: 'merge_with',
  review: 'review',
} as const;

export type EvaluateOrder200AddressDedupe = {
  matches?: EvaluateOrder200AddressDedupeMatchesItem[];
  suggested_action?: EvaluateOrder200AddressDedupeSuggestedAction;
  /** @nullable */
  canonical_id?: string | null;
};

export type EvaluateOrder200ValidationsEmail = {
  /** Whether the validation passed */
  valid?: boolean;
  /** List of reason codes */
  reason_codes?: string[];
  /** Whether the result is disposable (for email) */
  disposable?: boolean;
};

export type EvaluateOrder200ValidationsPhone = {
  /** Whether the validation passed */
  valid?: boolean;
  /** List of reason codes */
  reason_codes?: string[];
  /** Whether the result is disposable (for email) */
  disposable?: boolean;
};

export type EvaluateOrder200ValidationsAddress = {
  /** Whether the address is valid */
  valid?: boolean;
  /** List of reason codes */
  reason_codes?: string[];
  /** Whether the address is a P.O. Box */
  po_box?: boolean;
  /** Whether postal code matches city */
  postal_city_match?: boolean;
  /** Whether the address is within bounds */
  in_bounds?: boolean;
};

export type EvaluateOrder200Validations = {
  email?: EvaluateOrder200ValidationsEmail;
  phone?: EvaluateOrder200ValidationsPhone;
  address?: EvaluateOrder200ValidationsAddress;
};

export type EvaluateOrder200 = {
  /** Order ID */
  order_id?: string;
  /**
   * Risk score (0-100)
   * @minimum 0
   * @maximum 100
   */
  risk_score?: number;
  /** Recommended action */
  action?: EvaluateOrder200Action;
  /** Order tags */
  tags?: string[];
  /** List of reason codes */
  reason_codes?: string[];
  customer_dedupe?: EvaluateOrder200CustomerDedupe;
  address_dedupe?: EvaluateOrder200AddressDedupe;
  validations?: EvaluateOrder200Validations;
  request_id?: string;
};

export type EvaluateOrder400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type EvaluateOrder400 = {
  error?: EvaluateOrder400Error;
  /** Request identifier */
  request_id?: string;
};

export type VerifyPhoneOtpBody = {
  /** Twilio Verify SID from validation response */
  verification_sid: string;
  /** OTP code entered by user */
  code: string;
};

export type VerifyPhoneOtp200 = {
  /** Whether OTP is valid */
  valid?: boolean;
  /** List of reason codes */
  reason_codes?: string[];
  request_id?: string;
};

export type VerifyPhoneOtp400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type VerifyPhoneOtp400 = {
  error?: VerifyPhoneOtp400Error;
  /** Request identifier */
  request_id?: string;
};

export type ValidateEmailBody = {
  /** The email address to validate */
  email: string;
};

export type ValidateEmail200 = {
  /** Whether the email is valid */
  valid?: boolean;
  /** Normalized email address */
  normalized?: string;
  /** Whether the email is from a disposable service */
  disposable?: boolean;
  /** Whether MX records were found */
  mx_found?: boolean;
  /** List of validation reason codes */
  reason_codes?: string[];
  request_id?: string;
  /** Cache TTL in seconds */
  ttl_seconds?: number;
};

export type ValidateEmail400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type ValidateEmail400 = {
  error?: ValidateEmail400Error;
  /** Request identifier */
  request_id?: string;
};

export type ValidatePhoneBody = {
  /** The phone number to validate */
  phone: string;
  /** Optional two-letter country code hint */
  country?: string;
  /** Request OTP for verification */
  request_otp?: boolean;
};

export type ValidatePhone200 = {
  /** Whether the phone number is valid */
  valid?: boolean;
  /** Phone number in E.164 format */
  e164?: string;
  /**
   * Country code
   * @nullable
   */
  country?: string | null;
  /** List of validation reason codes */
  reason_codes?: string[];
  request_id?: string;
  /** Cache TTL in seconds */
  ttl_seconds?: number;
  /**
   * Twilio Verify SID for OTP verification
   * @nullable
   */
  verification_sid?: string | null;
};

export type ValidatePhone400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type ValidatePhone400 = {
  error?: ValidatePhone400Error;
  /** Request identifier */
  request_id?: string;
};

export type ValidateAddressBodyAddress = {
  /** Street address line 1 */
  line1: string;
  /** Street address line 2 */
  line2?: string;
  /** City */
  city: string;
  /** State or province */
  state?: string;
  /** Postal code */
  postal_code: string;
  /**
   * Two-letter country code
   * @minLength 2
   * @maxLength 2
   */
  country: string;
};

export type ValidateAddressBody = {
  address: ValidateAddressBodyAddress;
};

export type ValidateAddress200Normalized = {
  /** Street address line 1 */
  line1?: string;
  /** Street address line 2 */
  line2?: string;
  /** City */
  city?: string;
  /** State or province */
  state?: string;
  /** Postal code */
  postal_code?: string;
  /** Two-letter country code */
  country?: string;
  /**
   * Latitude
   * @nullable
   */
  lat?: number | null;
  /**
   * Longitude
   * @nullable
   */
  lng?: number | null;
};

/**
 * @nullable
 */
export type ValidateAddress200Geo = {
  /** Latitude */
  lat?: number;
  /** Longitude */
  lng?: number;
  /** Geocoding confidence score */
  confidence?: number;
} | null;

export type ValidateAddress200 = {
  /** Whether the address is valid */
  valid?: boolean;
  normalized?: ValidateAddress200Normalized;
  /** @nullable */
  geo?: ValidateAddress200Geo;
  /** Whether the address is a P.O. Box */
  po_box?: boolean;
  /** Whether postal code matches city */
  postal_city_match?: boolean;
  /** List of validation reason codes */
  reason_codes?: string[];
  request_id?: string;
  /** Cache TTL in seconds */
  ttl_seconds?: number;
};

export type ValidateAddress400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type ValidateAddress400 = {
  error?: ValidateAddress400Error;
  /** Request identifier */
  request_id?: string;
};

export type ValidateTaxIdBody = {
  /** Type of tax ID (e.g., "vat", "euvat", "br_cnpj") */
  type: string;
  /** The tax ID number */
  value: string;
  /** Optional two-letter country code */
  country?: string;
};

export type ValidateTaxId200 = {
  /** Whether the tax ID is valid */
  valid?: boolean;
  /** Normalized tax ID */
  normalized?: string;
  /** List of validation reason codes */
  reason_codes?: string[];
  request_id?: string;
};

export type ValidateTaxId400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type ValidateTaxId400 = {
  error?: ValidateTaxId400Error;
  /** Request identifier */
  request_id?: string;
};

export type ValidateNameBody = {
  /** The name to validate and normalize */
  name: string;
};

export type ValidateName200 = {
  /** Whether the name is valid */
  valid?: boolean;
  /** Normalized name */
  normalized?: string;
  /** List of validation reason codes */
  reason_codes?: string[];
  request_id?: string;
};

export type ValidateName400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type ValidateName400 = {
  error?: ValidateName400Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * Current job status
 */
export type GetJobStatus200Status = typeof GetJobStatus200Status[keyof typeof GetJobStatus200Status];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetJobStatus200Status = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * Progress information (only available during processing)
 * @nullable
 */
export type GetJobStatus200Progress = {
  /** Total items to process */
  total?: number;
  /** Items processed so far */
  processed?: number;
  /** Completion percentage (0-100) */
  percentage?: number;
} | null;

export type GetJobStatus200 = {
  /** Unique job identifier */
  job_id?: string;
  /** Current job status */
  status?: GetJobStatus200Status;
  /**
   * Progress information (only available during processing)
   * @nullable
   */
  progress?: GetJobStatus200Progress;
  /**
   * URL to download results (only available when completed)
   * @nullable
   */
  result_url?: string | null;
  /**
   * Error message (only available when failed)
   * @nullable
   */
  error?: string | null;
  /** Job creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
  /** Request identifier */
  request_id?: string;
};

export type GetJobStatus401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type GetJobStatus401 = {
  error?: GetJobStatus401Error;
  /** Request identifier */
  request_id?: string;
};

export type GetJobStatus404Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type GetJobStatus404 = {
  error?: GetJobStatus404Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * Retrieves the list of projects for the authenticated user along with plan information
 * @summary List user's projects
 */
export const getUserProjects = <TData = AxiosResponse<GetUserProjects200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/projects`,options
    );
  }

/**
 * Creates a new project for the authenticated user
 * @summary Create new project
 */
export const createProject = <TData = AxiosResponse<CreateProject201>>(
    createProjectBody: CreateProjectBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/projects`,
      createProjectBody,options
    );
  }

/**
 * Deletes a project by ID for the authenticated user
 * @summary Delete project
 */
export const deleteProject = <TData = AxiosResponse<DeleteProject200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/projects/${id}`,options
    );
  }

/**
 * Retrieves the current plan and usage information for the authenticated user
 * @summary Get current user plan
 */
export const getUserPlan = <TData = AxiosResponse<UserPlanResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/user/plan`,options
    );
  }

/**
 * Updates the user's subscription plan
 * @summary Update user plan
 */
export const updateUserPlan = <TData = AxiosResponse<UserPlanResponse>>(
    updateUserPlanBody: UpdateUserPlanBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/user/plan`,
      updateUserPlanBody,options
    );
  }

/**
 * Returns all available subscription plans
 * @summary Get available plans
 */
export const getAvailablePlans = <TData = AxiosResponse<GetAvailablePlans200Item[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/public/plans`,options
    );
  }

/**
 * Checks if the user has enough validation quota remaining
 * @summary Check validation limits
 */
export const checkValidationLimits = <TData = AxiosResponse<CheckValidationLimits200>>(
    checkValidationLimitsBody: CheckValidationLimitsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/user/plan/usage/check`,
      checkValidationLimitsBody,options
    );
  }

/**
 * Creates a new user account with default project and API key
 * @summary Register new user
 */
export const registerUser = <TData = AxiosResponse<RegisterUser201>>(
    registerUserBody: RegisterUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register`,
      registerUserBody,options
    );
  }

/**
 * Authenticates a user and returns JWT token
 * @summary User login
 */
export const loginUser = <TData = AxiosResponse<LoginUser200>>(
    loginUserBody: LoginUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      loginUserBody,options
    );
  }

/**
 * Logs out the current user by clearing the session
 * @summary User logout
 */
export const logoutUser = <TData = AxiosResponse<LogoutUser200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/logout`,undefined,options
    );
  }

/**
 * Retrieves API keys for the authenticated project
 * @summary List API keys
 */
export const listApiKeys = <TData = AxiosResponse<ListApiKeys200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/api-keys`,options
    );
  }

/**
 * Generates a new API key for the authenticated project
 * @summary Create API key
 */
export const createApiKey = <TData = AxiosResponse<CreateApiKey201>>(
    createApiKeyBody: CreateApiKeyBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/api-keys`,
      createApiKeyBody,options
    );
  }

/**
 * Revokes an API key by setting its status to revoked
 * @summary Revoke API key
 */
export const revokeApiKey = <TData = AxiosResponse<RevokeApiKey200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v1/api-keys/${id}`,options
    );
  }

/**
 * Retrieves all webhooks for the authenticated project
 * @summary List webhooks
 */
export const listWebhooks = <TData = AxiosResponse<ListWebhooks200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/webhooks`,options
    );
  }

/**
 * Creates a new webhook subscription for the authenticated project
 * @summary Create webhook
 */
export const createWebhook = <TData = AxiosResponse<CreateWebhook201>>(
    createWebhookBody: CreateWebhookBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/webhooks`,
      createWebhookBody,options
    );
  }

/**
 * Deletes a webhook subscription
 * @summary Delete webhook
 */
export const deleteWebhook = <TData = AxiosResponse<DeleteWebhook200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v1/webhooks/${id}`,options
    );
  }

/**
 * Sends a sample payload to the provided webhook URL and returns the response. Useful for testing webhook configurations.
 * @summary Test Webhook
 */
export const testWebhook = <TData = AxiosResponse<TestWebhook200>>(
    testWebhookBody: TestWebhookBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/webhooks/test`,
      testWebhookBody,options
    );
  }

/**
 * Retrieves a list of all available validation rules and their configurations
 * @summary Get available rules
 */
export const getAvailableRules = <TData = AxiosResponse<GetAvailableRules200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/rules`,options
    );
  }

/**
 * Retrieves a catalog of all possible error codes and their descriptions
 * @summary Get error code catalog
 */
export const getErrorCodeCatalog = <TData = AxiosResponse<GetErrorCodeCatalog200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/rules/error-codes`,options
    );
  }

/**
 * Retrieves a catalog of all possible reason codes and their descriptions
 * @summary Get reason code catalog
 */
export const getReasonCodeCatalog = <TData = AxiosResponse<GetReasonCodeCatalog200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/rules/catalog`,options
    );
  }

/**
 * Tests rules against a sample payload and returns triggered rules
 * @summary Test rules against payload
 */
export const testRulesAgainstPayload = <TData = AxiosResponse<TestRulesAgainstPayload200>>(
    testRulesAgainstPayloadBody: TestRulesAgainstPayloadBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/rules/test`,
      testRulesAgainstPayloadBody,options
    );
  }

/**
 * Registers new custom validation rules for the project
 * @summary Register custom rules
 */
export const registerCustomRules = <TData = AxiosResponse<RegisterCustomRules201>>(
    registerCustomRulesBody: RegisterCustomRulesBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/rules/register`,
      registerCustomRulesBody,options
    );
  }

/**
 * Deletes a custom validation rule by its ID
 * @summary Delete custom rule
 */
export const deleteCustomRule = <TData = AxiosResponse<DeleteCustomRule200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v1/rules/${id}`,options
    );
  }

/**
 * Retrieves event logs for the project with optional filters
 * @summary Get event logs
 */
export const getLogs = <TData = AxiosResponse<GetLogs200>>(
    params?: GetLogsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/data/logs`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Retrieves personal access tokens for the authenticated user
 * @summary List Personal Access Tokens
 */
export const listPersonalAccessTokens = <TData = AxiosResponse<ListPersonalAccessTokens200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/pats`,options
    );
  }

/**
 * Creates a new personal access token for management API access
 * @summary Create Personal Access Token
 */
export const createPersonalAccessToken = <TData = AxiosResponse<CreatePersonalAccessToken201>>(
    createPersonalAccessTokenBody: CreatePersonalAccessTokenBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/pats`,
      createPersonalAccessTokenBody,options
    );
  }

/**
 * Revokes a personal access token by disabling it
 * @summary Revoke Personal Access Token
 */
export const revokePersonalAccessToken = <TData = AxiosResponse<RevokePersonalAccessToken200>>(
    tokenId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v1/pats/${tokenId}`,options
    );
  }

/**
 * Retrieves usage statistics for the project
 * @summary Get usage statistics
 */
export const getUsage = <TData = AxiosResponse<GetUsage200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/data/usage`,options
    );
  }

/**
 * Retrieves tenant settings including country defaults, formatting, and risk thresholds
 * @summary Get tenant settings
 */
export const getSettings = <TData = AxiosResponse<GetSettings200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/settings`,options
    );
  }

/**
 * Updates tenant settings including country defaults, formatting, and risk thresholds
 * @summary Update tenant settings
 */
export const updateSettings = <TData = AxiosResponse<UpdateSettings200>>(
    updateSettingsBody: UpdateSettingsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/v1/settings`,
      updateSettingsBody,options
    );
  }

/**
 * Initiates data erasure for GDPR/CCPA compliance
 * @summary Erase user data
 */
export const eraseData = <TData = AxiosResponse<EraseData202>>(
    eraseDataBody: EraseDataBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/data/erase`,
      eraseDataBody,options
    );
  }

/**
 * Creates a Stripe Checkout session with base plan and usage-based line items
 * @summary Create Stripe Checkout session
 */
export const createCheckoutSession = <TData = AxiosResponse<CreateCheckoutSession200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/billing/checkout`,undefined,options
    );
  }

/**
 * Creates a Stripe Customer Portal session for managing billing
 * @summary Create Stripe Customer Portal session
 */
export const createCustomerPortalSession = <TData = AxiosResponse<CreateCustomerPortalSession200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/billing/portal`,undefined,options
    );
  }

/**
 * Deletes a specific log entry
 * @summary Delete log entry
 */
export const deleteLog = <TData = AxiosResponse<DeleteLog200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/v1/logs/${id}`,options
    );
  }

/**
 * Performs basic address normalization without geocoding or external lookups.
 * @summary Normalize Address (Cheap)
 */
export const normalizeAddress = <TData = AxiosResponse<NormalizeAddress200>>(
    normalizeAddressBody: NormalizeAddressBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/normalize/address`,
      normalizeAddressBody,options
    );
  }

/**
 * Performs batch validation of emails, phones, addresses, or tax IDs asynchronously
 * @summary Batch validate data
 */
export const batchValidate = <TData = AxiosResponse<BatchValidate202>>(
    batchValidateBody: BatchValidateBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/batch/validate`,
      batchValidateBody,options
    );
  }

/**
 * Performs batch deduplication of customers or addresses asynchronously
 * @summary Batch deduplicate data
 */
export const batchDedupe = <TData = AxiosResponse<BatchDedupe202>>(
    batchDedupeBody: BatchDedupeBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/batch/dedupe`,
      batchDedupeBody,options
    );
  }

/**
 * Searches for existing customers using deterministic and fuzzy matching
 * @summary Deduplicate customer
 */
export const dedupeCustomer = <TData = AxiosResponse<DedupeCustomer200>>(
    dedupeCustomerBody: DedupeCustomerBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/dedupe/customer`,
      dedupeCustomerBody,options
    );
  }

/**
 * Searches for existing addresses using deterministic and fuzzy matching
 * @summary Deduplicate address
 */
export const dedupeAddress = <TData = AxiosResponse<DedupeAddress200>>(
    dedupeAddressBody: DedupeAddressBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/dedupe/address`,
      dedupeAddressBody,options
    );
  }

/**
 * Merges multiple customer or address records into a canonical one
 * @summary Merge deduplicated records
 */
export const mergeDeduplicated = <TData = AxiosResponse<MergeDeduplicated200>>(
    mergeDeduplicatedBody: MergeDeduplicatedBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/dedupe/merge`,
      mergeDeduplicatedBody,options
    );
  }

/**
 * Retrieves the status and results of an asynchronous job.
 * @summary Get job status
 */
export const getJobStatusById = <TData = AxiosResponse<GetJobStatusById200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/jobs/:id`,options
    );
  }

/**
 * Evaluates an order for deduplication, validation, and applies business rules
 * @summary Evaluate order for risk and rules
 */
export const evaluateOrder = <TData = AxiosResponse<EvaluateOrder200>>(
    evaluateOrderBody: EvaluateOrderBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/orders/evaluate`,
      evaluateOrderBody,options
    );
  }

/**
 * Verifies OTP sent to phone number
 * @summary Verify phone OTP
 */
export const verifyPhoneOtp = <TData = AxiosResponse<VerifyPhoneOtp200>>(
    verifyPhoneOtpBody: VerifyPhoneOtpBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/verify/phone`,
      verifyPhoneOtpBody,options
    );
  }

/**
 * Performs comprehensive email validation including format, MX records, and disposable detection
 * @summary Validate email address
 */
export const validateEmail = <TData = AxiosResponse<ValidateEmail200>>(
    validateEmailBody: ValidateEmailBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/validate/email`,
      validateEmailBody,options
    );
  }

/**
 * Validates a phone number and returns it in E.164 format
 * @summary Validate phone number
 */
export const validatePhone = <TData = AxiosResponse<ValidatePhone200>>(
    validatePhoneBody: ValidatePhoneBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/validate/phone`,
      validatePhoneBody,options
    );
  }

/**
 * Validates a physical address and normalizes it
 * @summary Validate address
 */
export const validateAddress = <TData = AxiosResponse<ValidateAddress200>>(
    validateAddressBody: ValidateAddressBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/validate/address`,
      validateAddressBody,options
    );
  }

/**
 * Validates a tax identification number
 * @summary Validate tax ID
 */
export const validateTaxId = <TData = AxiosResponse<ValidateTaxId200>>(
    validateTaxIdBody: ValidateTaxIdBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/validate/tax-id`,
      validateTaxIdBody,options
    );
  }

/**
 * Validates and normalizes a name string
 * @summary Validate name
 */
export const validateName = <TData = AxiosResponse<ValidateName200>>(
    validateNameBody: ValidateNameBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/v1/validate/name`,
      validateNameBody,options
    );
  }

/**
 * Retrieves the status and results of an asynchronous job
 * @summary Get job status
 */
export const getJobStatus = <TData = AxiosResponse<GetJobStatus200>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/v1/jobs/${id}`,options
    );
  }

export type GetUserProjectsResult = AxiosResponse<GetUserProjects200>
export type CreateProjectResult = AxiosResponse<CreateProject201>
export type DeleteProjectResult = AxiosResponse<DeleteProject200>
export type GetUserPlanResult = AxiosResponse<UserPlanResponse>
export type UpdateUserPlanResult = AxiosResponse<UserPlanResponse>
export type GetAvailablePlansResult = AxiosResponse<GetAvailablePlans200Item[]>
export type CheckValidationLimitsResult = AxiosResponse<CheckValidationLimits200>
export type RegisterUserResult = AxiosResponse<RegisterUser201>
export type LoginUserResult = AxiosResponse<LoginUser200>
export type LogoutUserResult = AxiosResponse<LogoutUser200>
export type ListApiKeysResult = AxiosResponse<ListApiKeys200>
export type CreateApiKeyResult = AxiosResponse<CreateApiKey201>
export type RevokeApiKeyResult = AxiosResponse<RevokeApiKey200>
export type ListWebhooksResult = AxiosResponse<ListWebhooks200>
export type CreateWebhookResult = AxiosResponse<CreateWebhook201>
export type DeleteWebhookResult = AxiosResponse<DeleteWebhook200>
export type TestWebhookResult = AxiosResponse<TestWebhook200>
export type GetAvailableRulesResult = AxiosResponse<GetAvailableRules200>
export type GetErrorCodeCatalogResult = AxiosResponse<GetErrorCodeCatalog200>
export type GetReasonCodeCatalogResult = AxiosResponse<GetReasonCodeCatalog200>
export type TestRulesAgainstPayloadResult = AxiosResponse<TestRulesAgainstPayload200>
export type RegisterCustomRulesResult = AxiosResponse<RegisterCustomRules201>
export type DeleteCustomRuleResult = AxiosResponse<DeleteCustomRule200>
export type GetLogsResult = AxiosResponse<GetLogs200>
export type ListPersonalAccessTokensResult = AxiosResponse<ListPersonalAccessTokens200>
export type CreatePersonalAccessTokenResult = AxiosResponse<CreatePersonalAccessToken201>
export type RevokePersonalAccessTokenResult = AxiosResponse<RevokePersonalAccessToken200>
export type GetUsageResult = AxiosResponse<GetUsage200>
export type GetSettingsResult = AxiosResponse<GetSettings200>
export type UpdateSettingsResult = AxiosResponse<UpdateSettings200>
export type EraseDataResult = AxiosResponse<EraseData202>
export type CreateCheckoutSessionResult = AxiosResponse<CreateCheckoutSession200>
export type CreateCustomerPortalSessionResult = AxiosResponse<CreateCustomerPortalSession200>
export type DeleteLogResult = AxiosResponse<DeleteLog200>
export type NormalizeAddressResult = AxiosResponse<NormalizeAddress200>
export type BatchValidateResult = AxiosResponse<BatchValidate202>
export type BatchDedupeResult = AxiosResponse<BatchDedupe202>
export type DedupeCustomerResult = AxiosResponse<DedupeCustomer200>
export type DedupeAddressResult = AxiosResponse<DedupeAddress200>
export type MergeDeduplicatedResult = AxiosResponse<MergeDeduplicated200>
export type GetJobStatusByIdResult = AxiosResponse<GetJobStatusById200>
export type EvaluateOrderResult = AxiosResponse<EvaluateOrder200>
export type VerifyPhoneOtpResult = AxiosResponse<VerifyPhoneOtp200>
export type ValidateEmailResult = AxiosResponse<ValidateEmail200>
export type ValidatePhoneResult = AxiosResponse<ValidatePhone200>
export type ValidateAddressResult = AxiosResponse<ValidateAddress200>
export type ValidateTaxIdResult = AxiosResponse<ValidateTaxId200>
export type ValidateNameResult = AxiosResponse<ValidateName200>
export type GetJobStatusResult = AxiosResponse<GetJobStatus200>
