services:
  postgres:
    image: postgres:16
    env_file: .env.local
    ports:
      - "5432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  valkey:
    image: valkey/valkey:7.2
    ports:
      - "6379:6379"
    command: ["--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env.local
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  dashboard:
    build:
      context: ../../ # Build context is the monorepo root
      dockerfile: apps/dashboard/Dockerfile.dev
    working_dir: /app
    volumes:
      # Mount the entire project source code into the container
      - ../../:/app
      # This named volume prevents the local mount from overwriting the
      # node_modules installed inside the image.
      - node_modules_dashboard:/app/node_modules
    # Override the command to run the Vite dev server
    # Using pnpm filter is more robust than `cd`
    command: sh -c "pnpm --filter @orbitcheck/dashboard run dev --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true # Recommended for reliable file watching in Docker
    depends_on:
      - api

  # --- API SERVICE (with Hot Reload) ---
  api:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile.dev
    env_file:
      - ../../apps/api/.env.local
    volumes:
      # Mount the entire project source code into the container
      - ../../:/app
      # Use a named volume to preserve node_modules from the image build
      - node_modules_api:/app/node_modules
    # Override the command to run the development server with tsx watch
    command: sh -c "pnpm --filter @orbitcheck/api run dev"
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8080:8080"
    # NOTE: Your dev server might not have a /health endpoint immediately.
    # You may need to comment out this healthcheck for the dev environment.
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  caddy:
      build: ./caddy
      ports:
        - "8081:80"
      volumes:
        - ./dev.Caddyfile:/etc/caddy/Caddyfile
        - ../../apps/site:/usr/share/caddy/site
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        api:
          condition: service_healthy
        postgres:
          condition: service_healthy
        valkey:
          condition: service_healthy



  prom:
    image: prom/prometheus:latest
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ../loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    volumes:
      - ../promtail/config.yml:/etc/promtail/config.yml
    depends_on:
      - loki


  statping:
    image: docker.io/dockurr/statping:0.93.0
    ports:
      - "8082:80"
    volumes:
      - statping_data:/app
    environment:
      - DATABASE=sqlite
    depends_on:
      - api

  uptime-kuma:
    image: louislam/uptime-kuma:1
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data
    restart: always
    depends_on:
      - caddy

volumes:
  pg_data: {}
  minio_data: {}
  grafana_data: {}
  loki_data: {}
  caddy_data: {}
  caddy_config: {}
  statping_data: {}
  uptime_kuma_data: {}
  node_modules_dashboard: {}
  node_modules_api: {}
