// src/client/types.gen.ts is generated by @hey-api/openapi-ts
import type {
    BatchDedupeData,
    BatchEvaluateOrdersData,
    BatchValidateData,
    CheckValidationLimitsData,
    CreateApiKeyData,
    CreateCheckoutSessionData,
    CreateCustomerPortalSessionData,
    CreatePersonalAccessTokenData,
    CreateProjectData,
    CreateUserData,
    CreateWebhookData,
    DedupeAddressData,
    DedupeCustomerData,
    DeleteCustomRuleData,
    DeleteLogData,
    DeleteProjectData,
    DeleteWebhookData,
    EraseDataData,
    EstimateRoiData,
    EvaluateOrderData,
    GetAvailablePlansData,
    GetAvailableRulesData,
    GetBuiltInRulesData,
    GetErrorCodeCatalogData,
    GetJobStatusByIdData,
    GetLogsData,
    GetReasonCodeCatalogData,
    GetSettingsData,
    GetUsageData,
    GetUserPlanData,
    GetUserProjectsData,
    ListApiKeysData,
    ListPersonalAccessTokensData,
    ListUsersData,
    ListWebhooksData,
    LoginUserData,
    LogoutUserData,
    MergeDeduplicatedData,
    NormalizeAddressData,
    RegisterCustomRulesData,
    RegisterUserData,
    RevokeApiKeyData,
    RevokePersonalAccessTokenData,
    TestRulesAgainstPayloadData,
    TestWebhookData,
    UpdateSettingsData,
    UpdateUserPlanData,
    ValidateAddressData,
    ValidateEmailData,
    ValidateNameData,
    ValidatePhoneData,
    ValidateTaxIdData,
    VerifyPhoneOtpData,
} from '../generated/fastify/types.gen.js';

export const routes = {
    // Auth
    auth: {
        loginUser: '/auth/login',
        registerUser: '/auth/register',
        logoutUser: '/auth/logout',
    },
    // V1
    v1: {
        // API Keys
        apiKeys: {
            listApiKeys: '/v1/api-keys',
            createApiKey: '/v1/api-keys',
            revokeApiKey: '/v1/api-keys/{id}',
        },
        // Webhooks
        webhooks: {
            listWebhooks: '/v1/webhooks',
            createWebhook: '/v1/webhooks',
            deleteWebhook: '/v1/webhooks/{id}',
            testWebhook: '/v1/webhooks/test',
        },
        // Rules
        rules: {
            getAvailableRules: '/v1/rules',
            getBuiltInRules: '/v1/rules/builtin',
            getErrorCodeCatalog: '/v1/rules/error-codes',
            getReasonCodeCatalog: '/v1/rules/catalog',
            testRulesAgainstPayload: '/v1/rules/test',
            registerCustomRules: '/v1/rules/register',
            deleteCustomRule: '/v1/rules/{id}',
        },
        // Validate
        validate: {
            validateEmail: '/v1/validate/email',
            validatePhone: '/v1/validate/phone',
            validateAddress: '/v1/validate/address',
            validateTaxId: '/v1/validate/tax-id',
            validateName: '/v1/validate/name',
        },
        // Orders
        orders: {
            evaluateOrder: '/v1/orders/evaluate',
        },
        // Verify
        verify: {
            verifyPhoneOtp: '/v1/verify/phone',
        },
        normalize: {
            normalizeAddress: '/v1/normalize/address',
        },
        // Dedupe
        dedupe: {
            dedupeCustomer: '/v1/dedupe/customer',
            dedupeAddress: '/v1/dedupe/address',
            mergeDeduplicated: '/v1/dedupe/merge',
        },
        // Batch
        batch: {
            batchValidate: '/v1/batch/validate',
            batchDedupe: '/v1/batch/dedupe',
            batchEvaluateOrders: '/v1/batch/orders',
        },
        // Data
        data: {
            getLogs: '/v1/data/logs',
            getUsage: '/v1/data/usage',
            eraseData: '/v1/data/erase',
        },
        // Logs
        logs: {
            deleteLog: '/v1/logs/{id}',
        },
        // Personal Access Tokens
        pats: {
            listPersonalAccessTokens: '/v1/pats',
            createPersonalAccessToken: '/v1/pats',
            revokePersonalAccessToken: '/v1/pats/{token_id}',
        },
        // Settings
        settings: {
            getSettings: '/v1/settings',
            updateSettings: '/v1/settings',
        },
        // Billing
        billing: {
            createCheckoutSession: '/v1/billing/checkout',
            createCustomerPortalSession: '/v1/billing/portal',
        },
        // Users
        users: {
            listUsers: '/v1/users',
            createUser: '/v1/users',
        },

        // Jobs
        jobs: {
            getJobStatusById: '/v1/jobs/{id}',
        },

        // Tools
        tools: {
            estimateRoi: '/public/roi/estimate',
        },
    },
    // Projects
    projects: {
        getUserProjects: '/projects',
        createProject: '/projects',
        deleteProject: '/projects/{id}',
    },
    // User
    user: {
        getUserPlan: '/user/plan',
        updateUserPlan: '/user/plan',
        checkValidationLimits: '/user/plan/usage/check',
    },
    // Public
    public: {
        getAvailablePlans: '/public/plans',
    },
} as const satisfies {
    auth: {
        loginUser: LoginUserData['url'];
        registerUser: RegisterUserData['url'];
        logoutUser: LogoutUserData['url'];
    };
    v1: {
        apiKeys: {
            listApiKeys: ListApiKeysData['url'];
            createApiKey: CreateApiKeyData['url'];
            revokeApiKey: RevokeApiKeyData['url'];
        };
        webhooks: {
            listWebhooks: ListWebhooksData['url'];
            createWebhook: CreateWebhookData['url'];
            deleteWebhook: DeleteWebhookData['url'];
            testWebhook: TestWebhookData['url'];
        };
        rules: {
            getAvailableRules: GetAvailableRulesData['url'];
            getBuiltInRules: GetBuiltInRulesData['url'];
            getErrorCodeCatalog: GetErrorCodeCatalogData['url'];
            getReasonCodeCatalog: GetReasonCodeCatalogData['url'];
            testRulesAgainstPayload: TestRulesAgainstPayloadData['url'];
            registerCustomRules: RegisterCustomRulesData['url'];
            deleteCustomRule: DeleteCustomRuleData['url'];
        };
        validate: {
            validateEmail: ValidateEmailData['url'];
            validatePhone: ValidatePhoneData['url'];
            validateAddress: ValidateAddressData['url'];
            validateTaxId: ValidateTaxIdData['url'];
            validateName: ValidateNameData['url'];
        };
        orders: {
            evaluateOrder: EvaluateOrderData['url'];
        };
        verify: {
            verifyPhoneOtp: VerifyPhoneOtpData['url'];
        };
        data: {
            getLogs: GetLogsData['url'];
            getUsage: GetUsageData['url'];
            eraseData: EraseDataData['url'];
        };
        logs: {
            deleteLog: DeleteLogData['url'];
        };
        pats: {
            listPersonalAccessTokens: ListPersonalAccessTokensData['url'];
            createPersonalAccessToken: CreatePersonalAccessTokenData['url'];
            revokePersonalAccessToken: RevokePersonalAccessTokenData['url'];
        };
        settings: {
            getSettings: GetSettingsData['url'];
            updateSettings: UpdateSettingsData['url'];
        };
        billing: {
            createCheckoutSession: CreateCheckoutSessionData['url'];
            createCustomerPortalSession: CreateCustomerPortalSessionData['url'];
        };
        users: {
            listUsers: ListUsersData['url'];
            createUser: CreateUserData['url'];
        }; normalize: {
            normalizeAddress: NormalizeAddressData['url'];
        }; dedupe: {
            dedupeCustomer: DedupeCustomerData['url'];
            dedupeAddress: DedupeAddressData['url'];
            mergeDeduplicated: MergeDeduplicatedData['url'];
        };
        batch: {
            batchValidate: BatchValidateData['url'];
            batchDedupe: BatchDedupeData['url'];
            batchEvaluateOrders: BatchEvaluateOrdersData['url'];
        };
        jobs: {
            getJobStatusById: GetJobStatusByIdData['url'];
        };
        tools: {
            estimateRoi: EstimateRoiData['url'];
        };
    };
    projects: {
        getUserProjects: GetUserProjectsData['url'];
        createProject: CreateProjectData['url'];
        deleteProject: DeleteProjectData['url'];
    };
    user: {
        getUserPlan: GetUserPlanData['url'];
        updateUserPlan: UpdateUserPlanData['url'];
        checkValidationLimits: CheckValidationLimitsData['url'];
    };
    public: {
        getAvailablePlans: GetAvailablePlansData['url'];
    };
};

export const runtimeRoutes = () => {
    return [
        ...Object.values(routes.v1.validate),
        ...Object.values(routes.v1.dedupe),
        ...Object.values(routes.v1.orders),
        ...Object.values(routes.v1.batch),
        ...Object.values(routes.v1.tools),
        ...Object.values(routes.v1.normalize),

    ];
};

export const publicRoutes = () => {
    return [
        ...Object.values(routes.auth),
        ...Object.values(routes.public),
    ];
}

export const managementRoutes = () => {
    return [
        ...Object.values(routes.v1.apiKeys),
        ...Object.values(routes.v1.webhooks),
        ...Object.values(routes.v1.rules),
        ...Object.values(routes.v1.logs),
        ...Object.values(routes.v1.pats),
        ...Object.values(routes.projects),
        ...Object.values(routes.user),
        ...Object.values(routes.public),
        ...Object.values(routes.v1.billing),
    ];
};

export const dashboardRoutes = () => {
    return [
        ...Object.values(routes.auth),
        ...Object.values(routes.v1.users),
        ...Object.values(routes.v1.settings),
        ...Object.values(routes.v1.data),
        ...Object.values(routes.v1.jobs),
        ...Object.values(routes.projects),
        ...Object.values(routes.user),
        ...Object.values(routes.public),
        ...Object.values(routes.v1.billing),
        ...Object.values(routes.v1.apiKeys),
        ...Object.values(routes.v1.webhooks),
        ...Object.values(routes.v1.logs),
        ...Object.values(routes.v1.pats),
        ...Object.values(routes.v1.rules),
        ...Object.values(routes.v1.normalize),

        ...Object.values(routes.v1.dedupe),
        ...Object.values(routes.v1.batch),
    ];
}

export const adminRoutes = () => {
    return [
        ...Object.values(routes.v1.users),
    ];
}
// Example Using the typed route with buildUrl()
// import { client } from './client/client.gen';
// const url = client.buildUrl<ShowPetByIdData>({
//   url: routes.showPetById,
//   path: { petId: 123 },
// }); // '/pets/123'