# inventory.yml
all:
  hosts:
    hetzner_server:
      ansible_host: 49.12.5.180
      ansible_ssh_private_key_file: ~/.ssh/orbitcheck_ed25519
      ansible_python_interpreter: /usr/bin/python3
  vars:
    admin_user: "adminuser"
    podman_user: "podmanuser"
    ghcr_username: "guillemso1er"
    admin_password_hashed: "{{ admin_password | password_hash('bcrypt') }}"
    ansible_become_pass: "{{ admin_password }}"
    hetzner_volume_id: 103854103
    volume_fs: "xfs" 