export const environment = {
    PORT: Number.parseInt(process.env.PORT || "8080", 10),
    DATABASE_URL: process.env.DATABASE_URL || "postgres://postgres:postgres@localhost:5432/orbicheck",
    REDIS_URL: process.env.REDIS_URL || "redis://localhost:6379",
    LOG_LEVEL: process.env.LOG_LEVEL || "info",
    NOMINATIM_URL: process.env.NOMINATIM_URL || "https://nominatim.openstreetmap.org",
    LOCATIONIQ_KEY: process.env.LOCATIONIQ_KEY || "",
    DISPOSABLE_LIST_URL: process.env.DISPOSABLE_LIST_URL || "https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.json",
    SENTRY_DSN: process.env.SENTRY_DSN || "",
    VIES_WSDL_URL: process.env.VIES_WSDL_URL || "https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl",
    RETENTION_DAYS: Number.parseInt(process.env.RETENTION_DAYS || "90", 10),
    RATE_LIMIT_COUNT: Number.parseInt(process.env.RATE_LIMIT_COUNT || "300", 10),
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID || "",
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN || "",
    TWILIO_VERIFY_SERVICE_SID: process.env.TWILIO_VERIFY_SERVICE_SID || "",
    TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER || "",
    S3_ENDPOINT: process.env.S3_ENDPOINT || "http://localhost:9000",
    S3_ACCESS_KEY: process.env.S3_ACCESS_KEY || "minioadmin",
    S3_SECRET_KEY: process.env.S3_SECRET_KEY || "minioadmin",
    S3_BUCKET: process.env.S3_BUCKET || "orbicheck",
    GOOGLE_GEOCODING_KEY: process.env.GOOGLE_GEOCODING_KEY || "",
    USE_GOOGLE_FALLBACK: process.env.USE_GOOGLE_FALLBACK === "true",
    JWT_SECRET: process.env.JWT_SECRET || (() => { throw new Error('JWT_SECRET must be set in environment'); })(),
    ENCRYPTION_KEY: process.env.ENCRYPTION_KEY || (() => { throw new Error('ENCRYPTION_KEY must be set in environment'); })(),
    SESSION_SECRET: process.env.SESSION_SECRET || crypto.randomBytes(32).toString('hex'),

    // OIDC configuration (optional)
    OIDC_ENABLED: process.env.OIDC_ENABLED === 'true',
    OIDC_CLIENT_ID: process.env.OIDC_CLIENT_ID,
    OIDC_CLIENT_SECRET: process.env.OIDC_CLIENT_SECRET,
    OIDC_PROVIDER_URL: process.env.OIDC_PROVIDER_URL, // e.g., https://accounts.google.com
    OIDC_REDIRECT_URI: process.env.OIDC_REDIRECT_URI || `http://localhost:${process.env.PORT || 3000}/auth/callback`,
};