export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
} as const;

export const ERROR_CODES = {
  INVALID_URL: 'invalid_url',
  MISSING_PAYLOAD: 'missing_payload',
  INVALID_TYPE: 'invalid_type',
  INVALID_IDS: 'invalid_ids',
  INVALID_INPUT: 'invalid_input',
  NOT_FOUND: 'not_found',
  UNAUTHORIZED: 'unauthorized',
  INVALID_TOKEN: 'invalid_token',
  NO_PROJECT: 'no_project',
  USER_EXISTS: 'user_exists',
  INVALID_CREDENTIALS: 'invalid_credentials',
  SERVER_ERROR: 'server_error',
  WEBHOOK_SEND_FAILED: 'send_failed',
  RATE_LIMITED: 'rate_limited',
  MISSING_JWT_SECRET: 'missing_jwt_secret',
  MISSING_ENCRYPTION_KEY: 'missing_encryption_key',
  ERASE_INVALID_REQUEST: 'erase_invalid_request',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_URL]: 'Valid HTTPS/HTTP URL required',
  [ERROR_CODES.MISSING_PAYLOAD]: 'Custom payload required for custom type',
  [ERROR_CODES.INVALID_TYPE]: 'Invalid payload_type',
  [ERROR_CODES.INVALID_IDS]: 'Invalid or mismatched IDs',
  [ERROR_CODES.INVALID_INPUT]: 'Data must be an array with 1-10000 items',
  [ERROR_CODES.NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.INVALID_TOKEN]: 'Invalid token',
  [ERROR_CODES.NO_PROJECT]: 'No default project found',
  [ERROR_CODES.USER_EXISTS]: 'User already exists',
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.SERVER_ERROR]: 'Internal server error',
  [ERROR_CODES.WEBHOOK_SEND_FAILED]: 'Failed to send webhook',
  [ERROR_CODES.RATE_LIMITED]: 'Rate limit exceeded',
  [ERROR_CODES.MISSING_JWT_SECRET]: 'JWT_SECRET must be set in environment',
  [ERROR_CODES.MISSING_ENCRYPTION_KEY]: 'ENCRYPTION_KEY must be set in environment',
  [ERROR_CODES.ERASE_INVALID_REQUEST]: 'INVALID_REQUEST',
} as const;

export const ERROR_CODE_DESCRIPTIONS: Record<string, { description: string, category: string, severity: 'low' | 'medium' | 'high' }> = {
  [ERROR_CODES.INVALID_URL]: { description: 'Invalid URL format provided', category: 'validation', severity: 'low' },
  [ERROR_CODES.MISSING_PAYLOAD]: { description: 'Required payload missing for custom webhook type', category: 'validation', severity: 'low' },
  [ERROR_CODES.INVALID_TYPE]: { description: 'Invalid webhook payload type specified', category: 'validation', severity: 'low' },
  [ERROR_CODES.INVALID_IDS]: { description: 'Provided IDs are invalid or do not match', category: 'validation', severity: 'medium' },
  [ERROR_CODES.INVALID_INPUT]: { description: 'Invalid input data provided', category: 'validation', severity: 'medium' },
  [ERROR_CODES.NOT_FOUND]: { description: 'Resource not found', category: 'resource', severity: 'medium' },
  [ERROR_CODES.UNAUTHORIZED]: { description: 'Authentication required but not provided', category: 'auth', severity: 'high' },
  [ERROR_CODES.INVALID_TOKEN]: { description: 'Provided authentication token is invalid or expired', category: 'auth', severity: 'high' },
  [ERROR_CODES.NO_PROJECT]: { description: 'No default project configured for user', category: 'auth', severity: 'medium' },
  [ERROR_CODES.USER_EXISTS]: { description: 'User with provided credentials already exists', category: 'auth', severity: 'low' },
  [ERROR_CODES.INVALID_CREDENTIALS]: { description: 'Invalid login credentials provided', category: 'auth', severity: 'high' },
  [ERROR_CODES.SERVER_ERROR]: { description: 'Internal server error occurred', category: 'server', severity: 'high' },
  [ERROR_CODES.WEBHOOK_SEND_FAILED]: { description: 'Failed to deliver webhook to configured endpoint', category: 'webhook', severity: 'high' },
  [ERROR_CODES.RATE_LIMITED]: { description: 'Request rate limit exceeded', category: 'rate_limit', severity: 'medium' },
};