openapi: 3.0.3
info:
  title: OrbiCheck API
  description: API for validation, deduplication, and risk assessment services
  version: 1.0.0
  contact:
    name: OrbiCheck Team
    email: support@orbitcheck.io
servers:
  - url: https://api.orbitcheck.io/v1
    description: Production server
  - url: https://dev-api.orbitcheck.io/v1
    description: Development server
security:
  - BearerAuth: []
tags:
  - name: Internal
    description: Internal endpoints for system administration and maintenance.
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Internal JWT token for system administration
  schemas:
    Error:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: Error code
            message:
              type: string
              description: Error message
        request_id:
          type: string
          description: Request identifier
    ApiKey:
      type: object
      properties:
        id:
          type: string
          description: API key ID
        prefix:
          type: string
          description: API key prefix (first 6 characters)
        status:
          type: string
          enum:
            - active
            - revoked
          description: API key status
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        last_used_at:
          type: string
          format: date-time
          nullable: true
          description: Last used timestamp
    Webhook:
      type: object
      properties:
        id:
          type: string
          description: Webhook ID
        url:
          type: string
          format: uri
          description: Webhook URL
        events:
          type: array
          items:
            type: string
          description: Events this webhook is subscribed to
        status:
          type: string
          enum:
            - active
            - inactive
            - deleted
          description: Webhook status
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        last_fired_at:
          type: string
          format: date-time
          nullable: true
          description: Last time webhook was fired
    Address:
      type: object
      properties:
        line1:
          type: string
          description: Street address line 1
        line2:
          type: string
          description: Street address line 2
        city:
          type: string
          description: City
        state:
          type: string
          description: State or province
        postal_code:
          type: string
          description: Postal code
        country:
          type: string
          description: Two-letter country code
        lat:
          type: number
          nullable: true
          description: Latitude
        lng:
          type: number
          nullable: true
          description: Longitude
    Customer:
      type: object
      properties:
        email:
          type: string
          description: Customer email
        phone:
          type: string
          description: Customer phone
        first_name:
          type: string
          description: Customer first name
        last_name:
          type: string
          description: Customer last name
    CustomerMatch:
      type: object
      properties:
        id:
          type: string
          description: Customer ID
        similarity_score:
          type: number
          description: Similarity score (0-1)
        match_type:
          type: string
          enum:
            - exact_email
            - exact_phone
            - fuzzy_name
          description: Type of match
        data:
          $ref: '#/components/schemas/Customer'
    AddressMatch:
      type: object
      properties:
        id:
          type: string
          description: Address ID
        similarity_score:
          type: number
          description: Similarity score (0-1)
        match_type:
          type: string
          enum:
            - exact_address
            - exact_postal
            - fuzzy_address
          description: Type of match
        data:
          $ref: '#/components/schemas/Address'
    DedupeResult:
      type: object
      properties:
        matches:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              similarity_score:
                type: number
              match_type:
                type: string
              data:
                type: object
        suggested_action:
          type: string
          enum:
            - create_new
            - merge_with
            - review
        canonical_id:
          type: string
          nullable: true
    ValidationResult:
      type: object
      properties:
        valid:
          type: boolean
          description: Whether the validation passed
        reason_codes:
          type: array
          items:
            type: string
          description: List of reason codes
        disposable:
          type: boolean
          description: Whether the result is disposable (for email)
    AddressValidationResult:
      type: object
      properties:
        valid:
          type: boolean
          description: Whether the address is valid
        reason_codes:
          type: array
          items:
            type: string
          description: List of reason codes
        po_box:
          type: boolean
          description: Whether the address is a P.O. Box
        postal_city_match:
          type: boolean
          description: Whether postal code matches city
        in_bounds:
          type: boolean
          description: Whether the address is within bounds
    LogEntry:
      type: object
      properties:
        id:
          type: string
          description: Log entry ID
        type:
          type: string
          description: Log entry type
        endpoint:
          type: string
          description: API endpoint
        reason_codes:
          type: array
          items:
            type: string
          description: List of reason codes
        status:
          type: integer
          description: HTTP status code
        meta:
          type: object
          description: Additional metadata
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
    Rule:
      type: object
      properties:
        id:
          type: string
          description: Rule ID
        name:
          type: string
          description: Rule name
        description:
          type: string
          description: Rule description
        category:
          type: string
          description: Rule category
        enabled:
          type: boolean
          description: Whether the rule is enabled
    ReasonCode:
      type: object
      properties:
        code:
          type: string
          description: Reason code
        description:
          type: string
          description: Description of the reason code
        category:
          type: string
          description: Category of the reason code
        severity:
          type: string
          enum:
            - low
            - medium
            - high
          description: Severity level
    ErrorCode:
      type: object
      properties:
        code:
          type: string
          description: Error code
        description:
          type: string
          description: Description of the error code
        category:
          type: string
          description: Category of the error code
        severity:
          type: string
          enum:
            - low
            - medium
            - high
          description: Severity level
    CustomRule:
      type: object
      properties:
        id:
          type: string
          description: Rule ID
        name:
          type: string
          description: Rule name
        description:
          type: string
          description: Rule description
        reason_code:
          type: string
          description: Reason code to trigger
        severity:
          type: string
          enum:
            - low
            - medium
            - high
          description: Severity level
        enabled:
          type: boolean
          description: Whether the rule is enabled
