/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * OrbitCheck API
 * API for validation, deduplication, and risk assessment services
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type ErrorError = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export interface Error {
  error?: ErrorError;
  /** Request identifier */
  request_id?: string;
}

export interface User {
  /** User ID */
  id: string;
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** Creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
}

export interface LoginRequest {
  /** User email address */
  email: string;
  /** User password */
  password: string;
}

export type LoginResponseUser = {
  /** User ID */
  id: string;
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** Creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
};

export interface LoginResponse {
  /** JWT authentication token */
  token: string;
  user: LoginResponseUser;
  /** Request identifier */
  request_id?: string;
}

export interface CreateUserRequest {
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** User password (optional for admin creation) */
  password?: string;
}

export interface Pagination {
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of items */
  total: number;
  /** Total number of pages */
  total_pages: number;
}

export type LoginUserBody = {
  /** User email address */
  email: string;
  /** User password */
  password: string;
};

export type LoginUser200User = {
  /** User ID */
  id: string;
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** Creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
};

export type LoginUser200 = {
  /** JWT authentication token */
  token: string;
  user: LoginUser200User;
  /** Request identifier */
  request_id?: string;
};

export type LoginUser401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type LoginUser401 = {
  error?: LoginUser401Error;
  /** Request identifier */
  request_id?: string;
};

export type ListUsersParams = {
/**
 * Page number
 */
page?: number;
/**
 * Number of items per page
 */
limit?: number;
};

export type ListUsers200DataItem = {
  /** User ID */
  id: string;
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** Creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
};

export type ListUsers200Pagination = {
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of items */
  total: number;
  /** Total number of pages */
  total_pages: number;
};

export type ListUsers200 = {
  data?: ListUsers200DataItem[];
  pagination?: ListUsers200Pagination;
};

export type ListUsers401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type ListUsers401 = {
  error?: ListUsers401Error;
  /** Request identifier */
  request_id?: string;
};

export type CreateUserBody = {
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** User password (optional for admin creation) */
  password?: string;
};

export type CreateUser201 = {
  /** User ID */
  id: string;
  /** User email address */
  email: string;
  /** User first name */
  first_name: string;
  /** User last name */
  last_name: string;
  /** Creation timestamp */
  created_at?: string;
  /** Last update timestamp */
  updated_at?: string;
};

export type CreateUser400Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type CreateUser400 = {
  error?: CreateUser400Error;
  /** Request identifier */
  request_id?: string;
};

export type CreateUser401Error = {
  /** Error code */
  code?: string;
  /** Error message */
  message?: string;
};

export type CreateUser401 = {
  error?: CreateUser401Error;
  /** Request identifier */
  request_id?: string;
};

/**
 * Authenticates a user and returns JWT token
 * @summary User login
 */
export const loginUser = <TData = AxiosResponse<LoginUser200>>(
    loginUserBody: LoginUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      loginUserBody,options
    );
  }

/**
 * Retrieves a list of users
 * @summary List users
 */
export const listUsers = <TData = AxiosResponse<ListUsers200>>(
    params?: ListUsersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * Creates a new user
 * @summary Create user
 */
export const createUser = <TData = AxiosResponse<CreateUser201>>(
    createUserBody: CreateUserBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/users`,
      createUserBody,options
    );
  }

export type LoginUserResult = AxiosResponse<LoginUser200>
export type ListUsersResult = AxiosResponse<ListUsers200>
export type CreateUserResult = AxiosResponse<CreateUser201>
