# name: OpenAPI Validation

# on:
#   push:
#     branches: [ main, develop ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   validate-openapi:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4

#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '20'
#         cache: 'pnpm'

#     - name: Install dependencies
#       run: pnpm install

#     - name: Generate OpenAPI types
#       run: |
#         cd packages/contracts
#         pnpm dlx openapi-typescript openapi.yaml -o src/openapi-types.ts

#     - name: Validate OpenAPI specification
#       run: |
#         cd packages/contracts
#         pnpm dlx openapi-typescript openapi.yaml --strict

#     - name: Generate orval client
#       run: |
#         cd packages/contracts
#         pnpm orval

#     - name: Check for breaking changes
#       run: |
#         cd packages/contracts
#         # Check if generated files changed
#         if ! git diff --quiet src/openapi-types.ts src/api-client/; then
#           echo "Breaking changes detected in OpenAPI specification!"
#           echo "Please review the changes and update API clients accordingly."
#           git diff src/openapi-types.ts src/api-client/
#           exit 1
#         fi

#     - name: Run API tests
#       run: |
#         cd apps/api
#         pnpm test

#     - name: Build dashboard
#       run: |
#         cd apps/dashboard
#         pnpm build
